# Netlify Configuration
# This file configures how Netlify builds and deploys your site

[build]
  # Build command for the React application
  command = "cd themes/toha && npm install && cd ../.. && npm install && cd src && rm -rf node_modules package-lock.json && npm install && npm run build && cd .. && hugo --gc --minify"
  # Directory containing the built files
  publish = "public"

# Environment variables documentation
# These variables must be set in Netlify's dashboard:
# Site settings > Build & deploy > Environment
[build.environment]
  # Node version for the build
  NODE_VERSION = "18"
  # Ensure clean installs
  NPM_FLAGS = "--legacy-peer-deps"
  # Disable secrets scanning for build output
  SECRETS_SCAN_ENABLED = "false"
  HUGO_VERSION = "0.146.0"
  HUGO_EXTENDED = "true"

# Redirects for SPA
[[redirects]]
  from = "/api/*"
  to = "https://api.200rx.com/:splat"
  status = 200
  force = true

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), interest-cohort=()"
    Content-Security-Policy = "default-src 'self' https: 'unsafe-inline' 'unsafe-eval'; img-src 'self' https: data:; connect-src 'self' https://api.200rx.com https://*.netlify.app; frame-ancestors 'none';"